# Generated by Django 5.0.3 on 2024-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfficeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('event_location', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('warehouse_location', models.CharField(max_length=20)),
                ('unique_identifier', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
