# Generated by Django 5.0.3 on 2024-03-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanagement', '0002_rename_unique_identifier_outofficeproduct_event_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutOfficeProduct',
            new_name='EventDetails',
        ),
    ]
