# Generated by Django 5.0.3 on 2024-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanagement', '0003_rename_outofficeproduct_eventdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255)),
                ('event_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
