# Generated by Django 5.0.3 on 2024-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanagement', '0004_eventproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='remark_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
