# Generated by Django 5.0.3 on 2024-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanagement', '0005_eventdetails_remark_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='person_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
