# Generated by Django 4.0.6 on 2024-05-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanagement', '0006_eventdetails_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporaryaddeventdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=10, null=True)),
                ('serial_number', models.CharField(max_length=50, null=True)),
                ('remark_note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
