# Generated by Django 5.0.3 on 2024-03-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('serial_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('configuration', models.TextField()),
                ('working_status', models.CharField(default='working', max_length=10)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('buy_date', models.DateField()),
                ('brand_name', models.CharField(max_length=255)),
                ('office_status', models.CharField(default='office', max_length=255)),
            ],
        ),
    ]
