# Generated by Django 5.0.3 on 2024-03-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_product', '0002_product_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='event_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='office_status',
            field=models.CharField(max_length=255),
        ),
    ]
