# Generated by Django 4.0.6 on 2024-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_product', '0003_alter_product_event_name_alter_product_office_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='configuration',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
